#define TRUE 1
#define FALSE 0

#define SCREEN_WIDTH 1280
#define SCREEN_HEIGHT 720

#define	MAX_KEYBOARD_KEYS 350

#define LEVEL_NUMBER 10

#define TILE_SIZE 30
#define TILE_TYPE 8


#define FILE_NAME_SIZE 50

#define BOARD_WIDTH 114
#define BOARD_HEIGHT 40

#define TEXT_NUMBER 8

#define CHUNK_VOLUME 20
#define MUSIC_VOLUME 9
#define MAX_LINE 255



#define STANDING 2
#define RIGHT_WALKING 3
#define LEFT_WALKING 3
#define UP_WALKING 4
#define DOWN_WALKING 4

#define STANDING_FLAG 0
#define LEFT_WALKING_FLAG 1
#define RIGHT_WALKING_FLAG 2
#define UP_WALKING_FLAG 3
#define DOWN_WALKING_FLAG 4


#define DIAMOND_TILE__TYPE_AMOUNT 4
#define LEVELPORT_TILE__TYPE_AMOUNT 4
#define SPIDER_TILE__TYPE_AMOUNT 4

#define ROCK_TILE__TYPE_AMOUNT 3

#define BORDER_TILE__TYPE_AMOUNT 1
#define EARTH_TILE__TYPE_AMOUNT 1
#define EMPTY_TILE__TYPE_AMOUNT 1

#define MAX_FRAME_SPEED 6